# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[es]
  languageCode = "es-ar"
  contentDir = "content/es"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a third language.
[pt]
  languageCode = "pt-br"
  contentDir = "content/pt"
  title = "IEI-SudAqua"
  [pt.params]
    description = "Rede Colaborativa em Ecologia Microbiana Aquática da América Latina"
 # [[pt.menu.main]]
 #   name = "Início"
 #   url = "#home"
 #   weight = 10
    
[[pt.menu.main]]
  name = "Início"
  weight = 10
  identifier = "home"

[[pt.menu.main]]
  name = "Apresentação"
  url = "#home"
  weight = 10
  parent = "home"
  
[[pt.menu.main]]
  name = "Objetivos"
  url = "#aims"
  weight = 10
  parent = "home"

[[pt.menu.main]]
  name = "Redes Sociais"
  weight = 20
  identifier = "redes"

[[pt.menu.main]]
  name = "Youtube"
  url = "https://www.youtube.com/channel/UC9fbpMSqVo-ev5npXWlmkRQ"
  weight = 20
  parent = "redes"
  
[[pt.menu.main]]
  name = "Instagram"
  url = "https://www.instagram.com"
  weight = 20
  parent = "redes"

[[pt.menu.main]]
  name = "µSudAqua"
  weight = 30
  url = "https://microsudaqua.netlify.app/"
  identifier = "usud"
  