# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  weight = 10
  identifier = "home"

[[main]]
  name = "Presentación"
  url = "#home"
  weight = 10
  parent = "home"
  
[[main]]
  name = "Objetivos"
  url = "#aims"
  weight = 10
  parent = "home"

[[main]]
  name = "Redes Sociales"
  weight = 20
  identifier = "redes"

[[main]]
  name = "Youtube"
  url = "https://www.youtube.com/channel/UC9fbpMSqVo-ev5npXWlmkRQ"
  weight = 20
  parent = "redes"
  

[[main]]
  name = "Instagram"
  url = "https://www.instagram.com/microsudaqua/"
  weight = 20
  parent = "redes"

[[main]]
  name = "µSudAqua"
  weight = 30
  url = "https://microsudaqua.netlify.app/"
  identifier = "usud"
  